"""initial schema

Revision ID: 05d5f971a583
Revises:
Create Date: 2026-06-08 22:08:18.690090

This migration is SQLite-oriented: timestamp/JSON columns are sa.String()/
sa.Text() (ISO text / JSON text), matching the SQLite physical schema. The
authoritative PostgreSQL DDL (TIMESTAMPTZ/JSONB/vector) lives in
cctv_memory/infrastructure/db/postgres/schema.py, NOT in this migration; the ORM
models use with_variant so SQLite stays TEXT (see table-schema-spec §1.1bis).
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '05d5f971a583'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_policies',
    sa.Column('access_policy_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('security_level', sa.String(), nullable=False),
    sa.Column('rules_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('access_policy_id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_policy_tenant_name')
    )
    op.create_table('analysis_jobs',
    sa.Column('analysis_job_id', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('job_status', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('analysis_options_json', sa.Text(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('pipeline_version', sa.String(), nullable=True),
    sa.Column('created_record_ids_json', sa.Text(), nullable=False),
    sa.Column('updated_record_ids_json', sa.Text(), nullable=False),
    sa.Column('archived_record_ids_json', sa.Text(), nullable=False),
    sa.Column('failed_segment_ids_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('started_at', sa.String(), nullable=True),
    sa.Column('finished_at', sa.String(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('analysis_job_id'),
    sa.UniqueConstraint('idempotency_key', name='uq_jobs_idempotency')
    )
    with op.batch_alter_table('analysis_jobs', schema=None) as batch_op:
        batch_op.create_index('idx_jobs_status', ['job_status', 'created_at'], unique=False)
        batch_op.create_index('idx_jobs_video', ['video_id'], unique=False)

    op.create_table('analysis_scale_tasks',
    sa.Column('scale_task_id', sa.String(), nullable=False),
    sa.Column('analysis_job_id', sa.String(), nullable=False),
    sa.Column('analysis_scale', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_units', sa.Integer(), nullable=False),
    sa.Column('succeeded_units', sa.Integer(), nullable=False),
    sa.Column('failed_units', sa.Integer(), nullable=False),
    sa.Column('skipped_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('started_at', sa.String(), nullable=True),
    sa.Column('finished_at', sa.String(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('scale_task_id'),
    sa.UniqueConstraint('analysis_job_id', 'analysis_scale', name='uq_scaletask_job_scale')
    )
    op.create_table('analysis_tasks',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.String(), nullable=False),
    sa.Column('lease_owner', sa.String(), nullable=True),
    sa.Column('lease_expires_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    with op.batch_alter_table('analysis_tasks', schema=None) as batch_op:
        batch_op.create_index('idx_tasks_claim', ['status', 'next_run_at', 'priority'], unique=False)
        batch_op.create_index('idx_tasks_lease', ['lease_expires_at'], unique=False)

    op.create_table('audit_events',
    sa.Column('audit_event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('principal_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('context_id', sa.String(), nullable=True),
    sa.Column('resource_scope_hash', sa.String(), nullable=True),
    sa.Column('record_ids_json', sa.Text(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=True),
    sa.Column('camera_id', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('audit_event_id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('idx_audit_event_type_time', ['event_type', 'created_at'], unique=False)
        batch_op.create_index('idx_audit_principal_time', ['principal_id', 'created_at'], unique=False)
        batch_op.create_index('idx_audit_request', ['request_id'], unique=False)

    op.create_table('backup_jobs',
    sa.Column('backup_job_id', sa.String(), nullable=False),
    sa.Column('backup_type', sa.String(), nullable=False),
    sa.Column('principal_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('manifest_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('finished_at', sa.String(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('backup_job_id')
    )
    op.create_table('camera_devices',
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('camera_name', sa.String(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('install_position_desc', sa.Text(), nullable=True),
    sa.Column('stream_uri', sa.String(), nullable=True),
    sa.Column('access_policy_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('camera_id')
    )
    with op.batch_alter_table('camera_devices', schema=None) as batch_op:
        batch_op.create_index('idx_camera_location', ['location_id'], unique=False)
        batch_op.create_index('idx_camera_policy', ['access_policy_id'], unique=False)
        batch_op.create_index('idx_camera_status', ['status'], unique=False)

    op.create_table('camera_locations',
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('building', sa.String(), nullable=True),
    sa.Column('floor', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('room_or_zone', sa.String(), nullable=True),
    sa.Column('location_desc', sa.Text(), nullable=True),
    sa.Column('access_policy_id', sa.String(), nullable=True),
    sa.Column('security_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('location_id')
    )
    with op.batch_alter_table('camera_locations', schema=None) as batch_op:
        batch_op.create_index('idx_locations_area', ['area'], unique=False)
        batch_op.create_index('idx_locations_policy', ['access_policy_id', 'security_level'], unique=False)

    op.create_table('high_freq_triggers',
    sa.Column('trigger_id', sa.String(), nullable=False),
    sa.Column('analysis_job_id', sa.String(), nullable=False),
    sa.Column('scale_task_id', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('trigger_start_ms', sa.Integer(), nullable=False),
    sa.Column('trigger_end_ms', sa.Integer(), nullable=False),
    sa.Column('motion_score', sa.Float(), nullable=True),
    sa.Column('change_score', sa.Float(), nullable=True),
    sa.Column('trigger_reason', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint('trigger_start_ms < trigger_end_ms', name='ck_trigger_time_order'),
    sa.PrimaryKeyConstraint('trigger_id'),
    sa.UniqueConstraint('idempotency_key', name='uq_trigger_idempotency')
    )
    op.create_table('observation_record_history',
    sa.Column('history_id', sa.String(), nullable=False),
    sa.Column('old_record_id', sa.String(), nullable=False),
    sa.Column('replaced_by_record_id', sa.String(), nullable=True),
    sa.Column('archived_by_analysis_job_id', sa.String(), nullable=False),
    sa.Column('archived_at', sa.String(), nullable=False),
    sa.Column('archive_reason', sa.String(), nullable=False),
    sa.Column('record_snapshot_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_table('observation_records',
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('analysis_job_id', sa.String(), nullable=False),
    sa.Column('analysis_scale', sa.String(), nullable=False),
    sa.Column('segment_start_ms', sa.Integer(), nullable=False),
    sa.Column('segment_end_ms', sa.Integer(), nullable=False),
    sa.Column('observed_start_time', sa.String(), nullable=False),
    sa.Column('observed_end_time', sa.String(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('static_description_text', sa.Text(), nullable=False),
    sa.Column('dynamic_description_text', sa.Text(), nullable=False),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.Column('clip_uri', sa.String(), nullable=True),
    sa.Column('thumbnail_uri', sa.String(), nullable=True),
    sa.Column('attributes_json', sa.Text(), nullable=False),
    sa.Column('access_policy_id', sa.String(), nullable=False),
    sa.Column('security_level', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('pipeline_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.CheckConstraint('segment_start_ms < segment_end_ms', name='ck_obs_time_order'),
    sa.PrimaryKeyConstraint('record_id'),
    sa.UniqueConstraint('video_id', 'segment_start_ms', 'segment_end_ms', 'analysis_scale', name='uq_obs_segment_scale')
    )
    with op.batch_alter_table('observation_records', schema=None) as batch_op:
        batch_op.create_index('idx_obs_camera_time', ['camera_id', 'observed_start_time', 'observed_end_time'], unique=False)
        batch_op.create_index('idx_obs_location_time', ['location_id', 'observed_start_time', 'observed_end_time'], unique=False)
        batch_op.create_index('idx_obs_observed_time', ['observed_start_time', 'observed_end_time'], unique=False)
        batch_op.create_index('idx_obs_policy', ['access_policy_id', 'security_level'], unique=False)
        batch_op.create_index('idx_obs_scale', ['analysis_scale'], unique=False)
        batch_op.create_index('idx_obs_video_time', ['video_id', 'segment_start_ms', 'segment_end_ms'], unique=False)

    op.create_table('principals',
    sa.Column('principal_id', sa.String(), nullable=False),
    sa.Column('principal_type', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('external_subject_id', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('roles_json', sa.Text(), nullable=False),
    sa.Column('groups_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('principal_id')
    )
    with op.batch_alter_table('principals', schema=None) as batch_op:
        batch_op.create_index('idx_principals_external_subject', ['external_subject_id'], unique=False)
        batch_op.create_index('idx_principals_tenant_status', ['tenant_id', 'status'], unique=False)

    op.create_table('schema_metadata',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('search_candidates',
    sa.Column('revision_id', sa.String(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('score_detail_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('revision_id', 'record_id')
    )
    with op.batch_alter_table('search_candidates', schema=None) as batch_op:
        batch_op.create_index('idx_candidates_revision_rank', ['revision_id', 'rank'], unique=False)

    op.create_table('search_contexts',
    sa.Column('context_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('principal_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('authorized_scope_hash', sa.String(), nullable=False),
    sa.Column('dataset_revision', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('default_revision_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('last_accessed_at', sa.String(), nullable=False),
    sa.Column('expires_at', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('context_id')
    )
    op.create_table('search_revisions',
    sa.Column('revision_id', sa.String(), nullable=False),
    sa.Column('context_id', sa.String(), nullable=False),
    sa.Column('parent_revision_id', sa.String(), nullable=True),
    sa.Column('op', sa.String(), nullable=False),
    sa.Column('op_params_json', sa.Text(), nullable=False),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('facets_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('revision_id')
    )
    op.create_table('video_sources',
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_uri', sa.String(), nullable=False),
    sa.Column('original_source_uri', sa.String(), nullable=True),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('video_start_time', sa.String(), nullable=False),
    sa.Column('video_end_time', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('source_status', sa.String(), nullable=False),
    sa.Column('external_source_id', sa.String(), nullable=True),
    sa.Column('access_policy_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('video_id'),
    sa.UniqueConstraint('camera_id', 'video_start_time', name='uq_video_camera_starttime')
    )
    with op.batch_alter_table('video_sources', schema=None) as batch_op:
        batch_op.create_index('idx_video_camera_time', ['camera_id', 'video_start_time', 'video_end_time'], unique=False)
        batch_op.create_index('idx_video_policy', ['access_policy_id'], unique=False)
        batch_op.create_index('idx_video_status', ['source_status'], unique=False)

    # ### end Alembic commands ###

    # --- FTS5 placeholders (table-schema-spec §5.3). Rebuildable, not fact source.
    # No search/ranking algorithm is implemented in Phase 1; these are schema only.
    op.execute(
        "CREATE VIRTUAL TABLE observation_static_fts "
        "USING fts5(record_id UNINDEXED, text)"
    )
    op.execute(
        "CREATE VIRTUAL TABLE observation_dynamic_fts "
        "USING fts5(record_id UNINDEXED, text)"
    )
    op.execute(
        "CREATE VIRTUAL TABLE observation_tags_fts "
        "USING fts5(record_id UNINDEXED, text)"
    )

    # --- Vector placeholder table (table-schema-spec §5.4). Optional in MVP.
    op.create_table(
        'observation_vectors',
        sa.Column('record_id', sa.String(), nullable=False),
        sa.Column('vector_type', sa.String(), nullable=False),
        sa.Column('embedding', sa.Text(), nullable=False),
        sa.Column('metadata_json', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('record_id', 'vector_type'),
    )

    # --- Seed schema_metadata (table-schema-spec §1.2).
    now = sa.func.strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
    schema_metadata = sa.table(
        'schema_metadata',
        sa.column('key', sa.String),
        sa.column('value', sa.String),
    )
    op.bulk_insert(
        schema_metadata,
        [
            {"key": "schema_version", "value": "v1"},
            {"key": "alembic_initial_revision", "value": revision},
        ],
    )
    op.execute(
        schema_metadata.insert().from_select(
            ['key', 'value'],
            sa.select(sa.literal('created_at'), now),
        )
    )
    op.execute(
        schema_metadata.insert().from_select(
            ['key', 'value'],
            sa.select(sa.literal('last_migration_at'), now),
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observation_vectors')
    op.execute("DROP TABLE IF EXISTS observation_tags_fts")
    op.execute("DROP TABLE IF EXISTS observation_dynamic_fts")
    op.execute("DROP TABLE IF EXISTS observation_static_fts")
    with op.batch_alter_table('video_sources', schema=None) as batch_op:
        batch_op.drop_index('idx_video_status')
        batch_op.drop_index('idx_video_policy')
        batch_op.drop_index('idx_video_camera_time')

    op.drop_table('video_sources')
    op.drop_table('search_revisions')
    op.drop_table('search_contexts')
    with op.batch_alter_table('search_candidates', schema=None) as batch_op:
        batch_op.drop_index('idx_candidates_revision_rank')

    op.drop_table('search_candidates')
    op.drop_table('schema_metadata')
    with op.batch_alter_table('principals', schema=None) as batch_op:
        batch_op.drop_index('idx_principals_tenant_status')
        batch_op.drop_index('idx_principals_external_subject')

    op.drop_table('principals')
    with op.batch_alter_table('observation_records', schema=None) as batch_op:
        batch_op.drop_index('idx_obs_video_time')
        batch_op.drop_index('idx_obs_scale')
        batch_op.drop_index('idx_obs_policy')
        batch_op.drop_index('idx_obs_observed_time')
        batch_op.drop_index('idx_obs_location_time')
        batch_op.drop_index('idx_obs_camera_time')

    op.drop_table('observation_records')
    op.drop_table('observation_record_history')
    op.drop_table('high_freq_triggers')
    with op.batch_alter_table('camera_locations', schema=None) as batch_op:
        batch_op.drop_index('idx_locations_policy')
        batch_op.drop_index('idx_locations_area')

    op.drop_table('camera_locations')
    with op.batch_alter_table('camera_devices', schema=None) as batch_op:
        batch_op.drop_index('idx_camera_status')
        batch_op.drop_index('idx_camera_policy')
        batch_op.drop_index('idx_camera_location')

    op.drop_table('camera_devices')
    op.drop_table('backup_jobs')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_request')
        batch_op.drop_index('idx_audit_principal_time')
        batch_op.drop_index('idx_audit_event_type_time')

    op.drop_table('audit_events')
    with op.batch_alter_table('analysis_tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_tasks_lease')
        batch_op.drop_index('idx_tasks_claim')

    op.drop_table('analysis_tasks')
    op.drop_table('analysis_scale_tasks')
    with op.batch_alter_table('analysis_jobs', schema=None) as batch_op:
        batch_op.drop_index('idx_jobs_video')
        batch_op.drop_index('idx_jobs_status')

    op.drop_table('analysis_jobs')
    op.drop_table('access_policies')
    # ### end Alembic commands ###
